---
- hosts: localhost
#  gather_facts: no

  tasks:

  - name: Include the variables from the YAML file
    include_vars: vars/variables.yml
    tags: always
    no_log: True

  - name:
    import_tasks: tasks/PVC_Get_Token.yml
    tags: always

  - name: 
    import_tasks: tasks/PVC_Get_TenantID.yml
    tags: tenant
