---
- hosts: asbpvc1r
  gather_facts: yes

  tasks:

  - name: Include the variables from the YAML file
    include_vars: vars/variables.yml
    tags: always

  - name:
    import_tasks: tasks/PVC_Get_Token.yml
    tags: always

  - name: 
    import_tasks: tasks/PVC_Get_TenantID.yml
    tags: always

  - name:
    import_tasks: tasks/PVC_DeployVM.yml
    tags: deploy
