---
- hosts: localhost
  vars_files: 
    - pvc_pass.yml
  tasks:
  - name: Check connectivity
    ping:

  - name: Gather information about projects
    os_project_info:
     auth:
      password: "{{ item.pw  }}"
    with_items: "{{ pvc_auth }}"
    register: result
  - debug:
      msg: "{{ result }}"

  - name: status sensu-services
    service:
      name: "{{ item }}"
      state: started
    with_items:
      - panko-api.service
      - openstack-swift-account.service

  - name: Ensure the PowerVC REST API service is reachable
    uri:
      url:  "{{ ansible_env.OS_AUTH_URL }}"
      validate_certs: no
      status_code: 200

  - name: 
    import_tasks: tasks/listen_port.yml

